name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py312h9d5906e_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hf90b1b7_3
  - control=0.10.2=pyhd8ed1ab_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=h32ff316_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudnn-dev=9.10.2.21=hca898b4_0
  - libcudss=0.7.0.20=hca898b4_1
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libflang=5.0.0=h6538335_20180525
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libmagma=2.9.0=hb6a17ea_3
  - libnvjitlink=12.9.86=hac47afa_2
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libtorch=2.8.0=cuda128_mkl_h0cdabd9_301
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-meta=5.0.0=0
  - matplotlib-base=3.10.7=py312h0ebf65c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2024.2.2=h57928b3_15
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numba=0.62.1=py312h9a042f1_0
  - numpy=2.3.4=py312ha72d056_0
  - openjpeg=2.5.3=h24db6dd_1
  - openmp=5.0.0=vc14_1
  - openssl=3.6.0=h725018a_0
  - optree=0.17.0=py312hf90b1b7_2
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.2=py312he5662c2_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh6a1d191_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.7=hce54a09_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=8_cp312
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pywin32=311=py312h829343e_1
  - pyyaml=6.0.3=py312h05f76fc_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h91ac024_0
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - slycot=0.6.0=py312h71e5c2a_2
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.2=py312he06e257_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - umap-learn=0.5.9.post2=py312h2e8e312_0
  - unicodedata2=17.0.0=py312he06e257_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312haa95532_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asciitree==0.3.3
      - click==8.3.0
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.1
      - cuda-python==13.0.3
      - deprecated==1.2.18
      - distinctipy==1.3.4
      - faiss-cpu==1.12.0
      - fasteners==0.20
      - fsspec==2025.9.0
      - h11==0.16.0
      - h5py==3.15.1
      - hdf5storage==0.2.2
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - kilosort==4.1.2
      - llvmlite==0.45.1
      - markupsafe==2.1.5
      - neo==0.14.3
      - numcodecs==0.15.1
      - pandas==2.3.3
      - pillow==12.0.0
      - prettytable==3.16.0
      - probeinterface==0.3.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.0
      - pyqt6-sip==13.10.2
      - pytz==2025.2
      - quantities==0.16.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - skops==0.13.0
      - sniffio==1.3.1
      - spikeinterface==0.103.1
      - torch==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - wrapt==1.17.3
      - zarr==2.18.7
